services:
  prosody:
    build:
      context: .
      target: prosody-dev
    ports:
      - "127.0.0.1:5222:5222"
      - "127.0.0.1:5281:5281"
    volumes:
      - ./confs/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua

  slidge-dummy:
    build:
      context: .
      target: slidge-dev
    command:
      - --legacy-module=slidge.plugins.dummy
      - --server=localhost
      - --jid=dummy.localhost
    volumes:
      - ./slidge:/slidge/slidge
      - ./assets:/slidge/assets
      - ./persistent/slidge/dummy:/var/lib/slidge
    depends_on:
      - prosody
    network_mode: "service:prosody"

  slidge-telegram:
    build:
      context: .
      target: slidge-dev
    command:
      - --legacy-module=slidge.plugins.telegram
      - --server=localhost
      - --jid=telegram.localhost
    volumes:
      - ./slidge:/slidge/slidge
      - ./persistent/tdlib:/tdlib
      - ./persistent/slidge/telegram:/var/lib/slidge
    depends_on:
      - prosody
    network_mode: "service:prosody"

  slidge-signal:
    build:
      context: .
      target: slidge-dev
    command:
      - --legacy-module=slidge.plugins.signal
      - --server=localhost
      - --jid=signal.localhost
    volumes:
      - ./slidge:/slidge/slidge
      - ./persistent/signald:/signald
      - ./persistent/slidge/signal:/var/lib/slidge
    depends_on:
      - prosody
      - signald
    network_mode: "service:prosody"

  slidge-messenger:
    build:
      context: .
      target: slidge-dev
    command:
      - --legacy-module=slidge.plugins.messenger
      - --server=localhost
      - --jid=facebook.localhost
      - --fb-dir=/fb
    volumes:
      - ./slidge:/slidge/slidge
      - ./persistent/fb:/fb
      - ./persistent/slidge/facebook:/var/lib/slidge
    depends_on:
      - prosody
    network_mode: "service:prosody"

  slidge-mattermost:
    build:
      context: .
      target: slidge-dev
    command:
      - --legacy-module=slidge.plugins.mattermost
      - --server=localhost
      - --jid=mattermost.localhost
    volumes:
      - ./slidge:/slidge/slidge
      - ./persistent/slidge/mattermost:/var/lib/slidge
    depends_on:
      - prosody
    network_mode: "service:prosody"

  signald:
    image: signald/signald:latest
    volumes:
      - ./persistent/signald:/signald
