services:
  prosody:
    build:
      context: .
      target: prosody-dev
    ports:
      - "127.0.0.1:5222:5222"
      - "127.0.0.1:5281:5281"
    volumes:
      - ./confs/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua

  slidge-dummy:
    build:
      context: .
      target: slidge-dev
    command:
      - --config=/slidge-example.ini
      - --legacy-module=slidge.plugins.dummy
      - --jid=dummy.localhost
    volumes:
      - ./slidge:/venv/lib/python3.9/site-packages/slidge
      - ./persistent:/var/lib/slidge
      - ./confs/slidge-example.ini:/slidge-example.ini
    depends_on:
      - prosody
    network_mode: "service:prosody"

  slidge-telegram:
    build:
      context: .
      target: slidge-dev
    command:
      - --config=/slidge-example.ini
      - --legacy-module=slidge.plugins.telegram
      - --jid=telegram.localhost
    volumes:
      - ./slidge:/venv/lib/python3.9/site-packages/slidge
      - ./persistent:/var/lib/slidge
      - ./confs/slidge-example.ini:/slidge-example.ini
    depends_on:
      - prosody
    network_mode: "service:prosody"

  slidge-signal:
    build:
      context: .
      target: slidge-dev
    command:
      - --config=/slidge-example.ini
      - --legacy-module=slidge.plugins.signal
      - --jid=signal.localhost
    volumes:
      - ./slidge:/venv/lib/python3.9/site-packages/slidge
      - ./persistent:/var/lib/slidge
      - ./persistent/signald:/signald
      - ./confs/slidge-example.ini:/slidge-example.ini
    depends_on:
      - prosody
      - signald
    network_mode: "service:prosody"

  slidge-facebook:
    build:
      context: .
      target: slidge-dev
    command:
      - --config=/slidge-example.ini
      - --legacy-module=slidge.plugins.facebook
      - --jid=facebook.localhost
    volumes:
      - ./slidge:/slidge/slidge
      - ./persistent:/var/lib/slidge
      - ./confs/slidge-example.ini:/slidge-example.ini
    depends_on:
      - prosody
    network_mode: "service:prosody"

  signald:
    image: signald/signald:0.20.0
    volumes:
      - ./persistent/signald:/signald
