[tool.poetry]
name = "slidge"
version = "0.1.0"
description = ""
authors = ["Nicolas Cedilnik <nicoco@nicoco.fr>"]

[tool.poetry.dependencies]
python = "^3.7"
slixmpp = { git = "https://lab.louiz.org/poezio/slixmpp", branch = "master" }
pysignald-async = "*"
SQLAlchemy = ">=1.3"
qrcode = ">=6.1"
Pillow = ">=8.1.0"
aiohttp = ">=3.7.3"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
pytest-asyncio = "*"
black = "*"
pylint = "*"
ipython = "*"
Sphinx = "^3.0.0"
sphinx-autodoc-typehints = "^1.11.1"
Pygments = "^2.8.0"
rope = "^0.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
