[tool.poetry]
name = "slidge"
version = "0.1.0"
description = ""
authors = ["Nicolas Cedilnik <nicoco@nicoco.fr>"]

[tool.poetry.dependencies]
python = "^3.9"
slixmpp = "^1.8.2"
qrcode = ">=7.3"
Pillow = ">=8.1.0"
aiohttp = ">=3.8.1"
ConfigArgParse = "^1.5.3"

aiotdlib = { version = "^0.18.0", optional = true }
pydantic = { version = "*", optional = true }
nextcord = { version = "^2.0.0-alpha.10", optional = true }
pysignald-async = { version = ">=0.1.11", optional = true }
mautrix-facebook = { version = "^0.4.0", optional = true }
mattermostdriver = { version = "^7.3.2", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "*"
black = "*"
pylint = "*"
Sphinx = "^4"
Pygments = "^2.8.0"
sphinx-rtd-theme = "^1.0.0"
sphinx-argparse = "^0.3.1"
sphinx-autoapi = "^1.8.4"
mypy = "^0.961"
#pytest-order = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
telegram = ["aiotdlib", "pydantic"]
discord = ["nextcord"]
signal = ["pysignald-async"]
facebook = ["mautrix-facebook"]
mattermost = ["mattermostdriver"]

[tool.poetry.scripts]
slidge = 'slidge.__main__:main'

[tool.mypy]
exclude = "slixpatch.py"
ignore_missing_imports = true

[tool.black]
exclude = "xep_*"